services:
  web:
    build: .
    image: backend-template:1.0
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: "service_healthy"
    volumes:
      - .:/app
    command: ["sh", "./entrypoint.sh"]
    restart: always

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend_template
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d backend_template"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
